<a href="https://colab.research.google.com/github/aeishugupta/Learning_journey/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
2+2

4

In [ ]:
32 * 2

64

In [ ]:
import numpy as np
print(np.__version__)

2.1.3


In [ ]:
arr = np.array([23,45,23])
print(arr)

[23 45 23]


In [ ]:
arr_22 = np.array([[2,3],[4,5]])
print(arr_22)

[[2 3]
 [4 5]]


In [ ]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.diag([2,4,6])

array([[2, 0, 0],
       [0, 4, 0],
       [0, 0, 6]])

In [ ]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
arr = np.array([10,20,30,40,50])
print(arr>45)

[False False False False  True]


In [ ]:
arr = np.arange(12)
arr.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
# fancy indexing and transpos

In [ ]:
#Mathematical Operations
a = np.array([3,2,3])
b = np.array([6,6,8])
a+b


array([ 9,  8, 11])

In [ ]:
a-b

array([-3, -4, -5])

In [ ]:
a*b

array([18, 12, 24])

In [ ]:
a/b

array([0.5       , 0.33333333, 0.375     ])

In [ ]:
# Scalar Operations
a + 10

array([13, 12, 13])

In [ ]:
b - 2

array([4, 4, 6])

In [ ]:
b * 2

array([12, 12, 16])

In [ ]:
a/2

array([1.5, 1. , 1.5])

In [ ]:
# Aggregation function
arr = np.array([5,10,15,20,25])
arr.sum()

np.int64(75)

In [ ]:
arr.mean()

np.float64(15.0)

In [ ]:
arr.max()

np.int64(25)

In [ ]:
arr.min()

np.int64(5)

In [ ]:
arr.var()

np.float64(50.0)

In [ ]:
arr.prod()

np.int64(375000)

In [ ]:
arr.std()

np.float64(7.0710678118654755)

In [ ]:
# Axis Operation
arr = np.array([[1,2,3],[4,5,6]])
arr.sum(axis=0)

array([5, 7, 9])

In [ ]:
arr.sum(axis=1)

array([ 6, 15])

In [ ]:
# Universal Functions

arr = np.array([3,4,6,9,16])
np.sqrt(arr)

array([1.73205081, 2.        , 2.44948974, 3.        , 4.        ])

In [ ]:
np.sin(arr)

array([ 0.14112001, -0.7568025 , -0.2794155 ,  0.41211849, -0.28790332])

In [ ]:
np.cos(arr)

array([-0.9899925 , -0.65364362,  0.96017029, -0.91113026, -0.95765948])

In [ ]:
np.log(arr)

array([1.09861229, 1.38629436, 1.79175947, 2.19722458, 2.77258872])

In [ ]:
np.sort(arr)

array([ 3,  4,  6,  9, 16])

In [ ]:
np.where(arr==4)

(array([1]),)